#!/bin/sh

EXPECTED_ARGS=2
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: `basename $0` inputfile rawoutputfile"
  exit $E_BADARGS
fi

ffmpeg -i $1 -r 22 -f rawvideo -s 128x104 -pix_fmt rgb565be $2

